### ISSUE TITLE
Enable travis CI for automated testing of PRs

### ISSUE THREAD

**Issue by mitchmindtree** [JeffBelgum/ntp#19]
Would you be interested in this? If so, I imagine a super simple `.travis.yml` config would be sufficient, something like this:
```yml
language: rust
rust:
    - nightly
    - beta
    - stable
script:
    - cargo build --verbose
    - cargo test --verbose
    - cargo doc --verbose
```
